// Sort Date 2/9/2023

import { CHAIN_TYPE } from './chainIds'
import { COIN_IMAGE } from './chainUtils'

export const CHAIN_DATA: Record<string, any> = {
  multiChain: {
    isSystem: true,
    isMnemonicOnly: true,
    name: 'Multi-Chain',
    icon: 'app_multi_chain',
    chain: CHAIN_TYPE.multiChain,
    tokenStandard: 'All Blockchains',
  },

  evm: {
    isSystem: true,
    name: 'EVM Wallet',
    icon: 'app_evm',
    chain: CHAIN_TYPE.evm,
    tokenStandard: 'EVM Wallet',
    isExcluded: true,
  },

  hardwareWallet: {
    isSystem: true,
    isHardware: true,
    name: 'Hardware Wallet',
    icon: 'app_ledger',
    chain: CHAIN_TYPE.hardwareWallet,
    tokenStandard: 'Cold Wallet',
  },

  trezorWallet: {
    isSystem: true,
    isHardware: true,
    name: 'Trezor EVM Wallet',
    icon: 'app_trezor_hardware',
    chain: CHAIN_TYPE.trezor,
    tokenStandard: 'Trezor',
  },

  legderEVMWallet: {
    isSystem: true,
    isHardware: true,
    name: 'Ledger EVM Wallet',
    icon: 'app_ledger_hardware',
    chain: CHAIN_TYPE.ledger_evm,
    tokenStandard: 'Legder',
  },

  legderSOLWallet: {
    isSystem: true,
    isHardware: true,
    name: 'Ledger SOL Wallet',
    icon: 'app_ledger_hardware',
    chain: CHAIN_TYPE.ledger_sol,
    tokenStandard: 'Legder',
  },

  customCreate: {
    isSystem: true,
    name: 'Custom Network',
    icon: 'app_custom_network',
    chain: CHAIN_TYPE.customCreate,
    tokenStandard: 'Create Custom Network',
    isExcluded: true,
  },
  custom: {
    isSystem: true,
    name: 'Custom Network',
    icon: 'app_box',
    chain: CHAIN_TYPE.custom,
    tokenStandard: 'Custom Network',
    isExcluded: true,
  },

  bitcoin: {
    order: 5,
    isFee: true,
    isMnemonicOnly: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    icon: 'app_bitcoin',
    id: 'bitcoin',
    name: 'Bitcoin',
    shortName: 'Bitcoin',
    logo: COIN_IMAGE.BTC,
    symbol: 'BTC',
    chain: CHAIN_TYPE.bitcoin,
    tokenStandard: 'BTC',
    scan: 'https://mempool.space',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
    gasUnit: 'sats/vB',
  },
  bitcoinTestnet: {
    isFee: true,
    isMnemonicOnly: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    icon: 'app_bitcoin',
    id: 'bitcoin-test',
    name: 'Bitcoin testnet',
    shortName: 'Bitcoin testnet',
    logo: COIN_IMAGE.BTC,
    symbol: 'TBTC',
    chain: CHAIN_TYPE.bitcoinTestnet,
    tokenStandard: 'BTC',
    scan: 'https://mempool.space/testnet',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
    environment: 'testnet',
  },
  ether: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    isDataField: true,
    numChainId: 1,
    chainId: '0x1',
    order: 1,
    isToken: true,
    standard: 'ERC20',
    nftStandard: 'ERC721',
    balanceContract: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multiTransferContract: '0x336b305cE67c748C646884191631f6B1502047eA',
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    icon: 'app_ethereum',
    id: 'ethereum',
    name: 'Ethereum',
    shortName: 'Ethereum',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    // replacementSymbol: 'ERC',
    chain: CHAIN_TYPE.ether,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: "https://ethereum-mainnet.core.chainstack.com/a3fbe23f5f39d8ebdd6541450be4a4c4",
    scan: 'https://etherscan.io',
  },
  etherPoW: {
    numChainId: 10001,
    chainId: '0x2711',
    // numLoad: 0,
    // isSupportedEIP1559: true,
    isToken: true,
    // isBridge: true,
    isSupportedNFT: true,

    standard: 'ERC20W',
    nftStandard: 'ERC721W',
    balanceContract: '0x38bb7b9b87bdfbed883aaf50a2f411d330fe32d6',
    multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    // stake: '0x836bf46520C373Fdc4dc7E5A3bAe735d13bD44e3',
    isSupportedV2: true,
    isWeb3: true,
    isFee: true,
    icon: 'app_ethereum_pow',
    id: 'ethereum-pow-iou',
    name: 'Ethereum PoW',
    shortName: 'ETHPoW',
    logo: COIN_IMAGE.ETHW,
    symbol: 'ETHW',
    chain: CHAIN_TYPE.etherPoW,
    tokenStandard: 'ETHW ERC20W ERC721W',
    rpcURL: 'https://mainnet.ethereumpow.org',
    scan: 'https://www.oklink.com/ethw',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',

  },
  binanceSmart: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    numChainId: 56,
    chainId: '0x38',
    order: 1,
    isToken: true,
    isSupportedNFT: true,
    nftStandard: 'BEP721',
    standard: 'BEP20',
    replacementSymbol: 'BSC',
    balanceContract: '0xA6762c710852681c4593C10c4304C5211FB2122c',
    multiTransferContract: '0x96465120138C032087ca1606f420ab4c8068f0cE',

    subName: 'BSC',

    isWeb3: true,
    isFee: true,
    icon: 'app_binance',

    id: 'binancecoin',
    name: 'BNB Smart Chain',
    shortName: 'BSC',
    logo: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: CHAIN_TYPE.binanceSmart,
    tokenStandard: 'BNB BEP20',
    rpcURL:
      'https://bsc-mainnet.nodereal.io/v1/2035a58b2c0d480d93a7e21acb6e460c',
    scan: 'https://bscscan.com',
  },
  heco: {
    numChainId: 128,
    chainId: '0x80',
    order: 1,
    isToken: true,
    isSupportedNFT: true,
    standard: 'HRC20',
    nftStandard: 'HRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_heco',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    // isSupportedEIP1559: true,

    id: 'huobi-token',
    name: 'HECO Chain',
    shortName: 'Huobi',
    logo: COIN_IMAGE.HT,
    symbol: 'HT',
    chain: CHAIN_TYPE.heco,
    tokenStandard: 'HT HRC20',
    rpcURL: 'https://go.getblock.io/cbb41430d8d048b19c995ad64bcf103c',
    scan: 'https://hecoscan.io/#',
    scanTxPrefix: 'transaction'
  },
  ancient8: {
    replacementSymbol: 'ANCIENT8',
    balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    numChainId: 28122024,
    chainId: '0x1ad1ba8',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_ancient8',
    environment: 'testnet',
    isL2: true,
    name: 'Ancient8 Testnet V2',
    shortName: 'ETH',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.ancient8,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpcv2-testnet.ancient8.gg',
    scan: 'https://scanv2-testnet.ancient8.gg',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  ancient8Mainnet: {
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    id: 'ethereum',
    // replacementSymbol: 'ANCIENT8',
    replacementSymbol: 'ANCIENT8',

    numChainId: 888888888,
    chainId: '0x34fb5e38',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isWeb3: true,
    isFee: true,
    icon: 'app_ancient8',
    isL2: true,
    name: 'Ancient8',
    shortName: 'ETH',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.ancient8Mainnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.ancient8.gg',
    scan: 'https://scan.ancient8.gg',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  berachain: {
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    numChainId: 80085,
    chainId: '0x138d5',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_berachain',
    environment: 'testnet',
    name: 'Berachain Testnet',
    shortName: 'BERA',
    symbol: 'BERA',
    symbolSuffix: 'TEST',
    chain: CHAIN_TYPE.berachain,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://artio.rpc.berachain.com',
    scan: 'https://artio.beratrail.io',
  },
  xaiNetwork: {
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    id: 'xai-blockchain',
    numChainId: 660279,
    chainId: '0xa1337',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_xainetwork',
    name: 'Xai Network',
    shortName: 'XAI',
    symbol: 'XAI',
    chain: CHAIN_TYPE.xaiNetwork,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://xai-chain.net/rpc',
    scan: 'https://explorer.xai-chain.net',
  },

  bitgert: {
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    id: 'bitrise-token',
    numChainId: 32520,
    chainId: '0x7f08',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_bitgert',
    name: 'Bitgert',
    shortName: 'BRISE',
    symbol: 'BRISE',
    chain: CHAIN_TYPE.bitgert,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://mainnet-rpc.brisescan.com',
    scan: 'https://brisescan.com',
  },
  // evmosEvm: {
  //   // multisend: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
  //   // balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  //   prefix: 'evmos',
  //   replacementSymbol: 'EVM',
  //   standard: 'ERC20',
  //   nftStandard: 'ERC721',
  //   isWeb3: true,
  //   isFee: true,
  //   shortName: 'EVMOS',
  //   numChainId: 9001,
  //   chainId: '0x2329',
  //   id: 'evmos',
  //   name: 'Evmos EVM',
  //   icon: 'app_evmos',
  //   symbol: 'EVMOS',
  //   logo: COIN_IMAGE.EVMOS,
  //   chain: CHAIN_TYPE.evmosEvm,
  //   tokenStandard: 'EVMOS',
  //   scan: 'https://escan.live',
  //   rpcURL: 'https://evmos.lava.build',
  //   scanTxPrefix: 'tx',
  //   scanAddressPrefix: 'address',
  // },
  kavaEvm: {
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    replacementSymbol: 'EVM',
    standard: 'EVM KRC20',
    nftStandard: 'EVM KRC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    shortName: 'KAVA',
    numChainId: 2222,
    chainId: '0x8ae',
    id: 'kava',
    name: 'Kava EVM',
    icon: 'app_kava',
    symbol: 'KAVA',
    logo: COIN_IMAGE.KAVA,
    chain: CHAIN_TYPE.kavaEvm,
    tokenStandard: 'KRC20 KRC721',
    scan: 'https://kavascan.com',
    rpcURL: 'https://evm.kava.io',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  confluxEvm: {
    // multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    // balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    replacementSymbol: 'eSpace',
    standard: 'eSpace CRC20',
    nftStandard: 'eSpace CRC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    shortName: 'CFX',
    numChainId: 1030,
    chainId: '0x406',
    id: 'conflux-token',
    name: 'Conflux eSpace',
    icon: 'app_conflux',
    symbol: 'CFX',
    logo: COIN_IMAGE.CFX,
    chain: CHAIN_TYPE.confluxEvm,
    tokenStandard: 'CRC20 CRC721',
    scan: 'https://evm.confluxscan.io',
    rpcURL: 'https://evm.confluxrpc.com',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  linea: {
    replacementSymbol: 'LINEA',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    numChainId: 59144,
    chainId: '0xe708',
    standard: 'LRC20',
    nftStandard: 'LRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_linea',

    id: 'ethereum',
    name: 'Linea',
    shortName: 'ETH',
    logo: COIN_IMAGE.ETH,
    isL2: true,
    symbol: 'ETH',
    chain: CHAIN_TYPE.linea,
    tokenStandard: 'LRC20 LRC721',
    rpcURL: 'https://1rpc.io/linea',
    scan: 'https://lineascan.build',
  },
  taiko: {
    replacementSymbol: 'TAIKO',
    numChainId: 167007,
    chainId: '0x28c5f',
    tokenStandard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_taiko',
    name: 'Taiko Jolnir Testnet',
    shortName: 'ETH',
    isL2: true,
    environment: 'testnet',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.taiko,
    standard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.jolnir.taiko.xyz',
    scan: 'https://explorer.jolnir.taiko.xyz'
  },
  taikoMainnet: {
    replacementSymbol: 'TAIKO',
    numChainId: 167000,
    isCrawlServices: true,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    chainId: '0x28c58',
    standard: 'ERC20 TAIKO',
    nftStandard: 'ERC721 TAIKO',
    isWeb3: true,
    isFee: true,
    isToken: true,
    icon: 'app_taiko',
    id: 'ethereum',
    name: 'Taiko',
    shortName: 'ETH',
    isL2: true,
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.taikoMainnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.taiko.xyz',
    scan: 'https://taikoscan.io/',
  },
  kroma: {
    replacementSymbol: 'KROMA',
    numChainId: 255,
    chainId: '0xff',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isL2: true,
    icon: 'app_kroma',

    id: 'ethereum',
    name: 'Kroma',
    shortName: 'ETH',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.kroma,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://api.kroma.network',
    scan: 'https://blockscout.kroma.network',
    gasOracleAddress: '0x4200000000000000000000000000000000000005'
  },
  coreDao: {
    numChainId: 1116,
    chainId: '0x45c',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_coredao',

    id: 'coredaoorg',
    name: 'Core',
    shortName: 'CORE',
    logo: COIN_IMAGE.CHZ,
    symbol: 'CORE',
    chain: CHAIN_TYPE.coreDao,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.coredao.org',
    scan: 'https://scan.coredao.org',
  },
  okex: {
    numChainId: 66,
    chainId: '0x42',
    order: 2,
    balanceContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isToken: true,
    isDataField: true,
    isSupportedNFT: true,
    id: 'oec-token',
    name: 'OKXChain',
    icon: 'app_okex',
    symbol: 'OKT',
    chain: CHAIN_TYPE.okex,
    logo: COIN_IMAGE.OKT,
    standard: 'KIP20',
    nftStandard: 'NFT',
    tokenStandard: 'OKT KIP10 KIP20 NFT',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://exchainrpc.okex.org',
    scan: 'https://www.oklink.com/okexchain',
  },
  terra2: {
    prefix: 'terra',
    path: 330,

    order: 3,
    isToken: true,
    standard: 'CW20',
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'terra-luna-2',
    chainId: 'phoenix-1',

    name: 'Terra 2.0',
    icon: 'app_terra2',
    symbol: 'LUNA',
    logo: COIN_IMAGE.LUNA2,
    chain: CHAIN_TYPE.terra2,
    tokenStandard: 'LUNA CW20',
    scan: 'https://finder.terra.money/mainnet',
  },

  band: {
    prefix: 'band',
    path: 494,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,

    id: 'band-protocol',
    chainId: 'laozi-mainnet',

    name: 'BandChain',
    icon: 'app_band',
    logo: COIN_IMAGE.BAND,
    symbol: 'BAND',
    tokenStandard: 'BAND',
    chain: CHAIN_TYPE.band,
    scan: 'https://cosmoscan.io',
    scanAddressPrefix: 'account',
  },

  gate: {
    numChainId: 86,
    chainId: '0x56',
    order: 2,
    balanceContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multiTransferContract: '0x963e1bcd1f82724bd8fa16a3b6962d100fb287fc',
    isSupportedNFT: true,
    isToken: true,
    isSupportedEIP1559: false,
    id: 'gatechain-token',
    name: 'GateChain',
    icon: 'app_gate',
    symbol: 'GT',
    chain: CHAIN_TYPE.gate,
    logo: COIN_IMAGE.GT,
    standard: 'GRC20',
    nftStandard: 'GRC721',
    tokenStandard: 'GT GRC20 GRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://evm.gatenode.cc',
    scan: 'https://gatescan.org',
  },

  kucoin: {
    numChainId: 321,
    chainId: '0x141',

    order: 2,
    isSupportedNFT: true,
    isToken: true,
    subName: 'KCS',
    standard: 'KRC20',
    nftStandard: 'KRC721',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    isWeb3: true,
    isFee: true,
    icon: 'kucoin',
    id: 'kucoin-shares',
    name: 'Kucoin Chain',
    shortName: 'KCC',
    logo: COIN_IMAGE.KCS,
    symbol: 'KCS',
    chain: CHAIN_TYPE.kucoin,
    tokenStandard: 'KCS KRC20 KRC721',
    rpcURL: 'https://rpc-mainnet.kcc.network',
    scan: 'https://scan.kcc.io/'
  },
  solana: {
    chainId: 'solana',
    isCrawlNFTServices: true,
    order: 1,
    isToken: true,
    standard: 'SPL',
    nftStandard: 'SPL NFT',
    isSupportedNFT: true,
    multiTransferContract: true,
    icon: 'app_solana',
    id: 'solana',
    name: 'Solana',
    shortName: 'Solana',
    logo: COIN_IMAGE.SOL,
    symbol: 'SOL',
    chain: CHAIN_TYPE.solana,
    gasUnit: 'lamports',
    tokenStandard: 'SOL SPL',
    rpcURL: 'https://information.coin98.com/api/solanaV4',
    scan: 'https://solscan.io',
  },
  near: {
    order: 2,
    icon: 'app_near',
    id: 'near',
    name: 'Near',
    logo: COIN_IMAGE.NEAR,
    symbol: 'NEAR',
    tokenStandard: 'NEAR NEP141',
    standard: 'NEP141',
    chain: CHAIN_TYPE.near,

    isToken: true,
    scan: 'https://nearblocks.io',
    rpcURL: 'https://free.rpc.fastnear.com',
    scanTxPrefix: 'txns',
    scanAddressPrefix: 'address',
    // isToken: true
  },
  avax: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    path: 9000,

    numChainId: 43114,
    chainId: '0xa86a',

    order: 1,
    isToken: true,
    nftStandard: 'ARC721',
    standard: 'ARC20',
    replacementSymbol: 'CCHAIN',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x9A35231fD7EEa8e7260BD4E4f5b57409caB35CBD',

    subName: 'C',
    isSupportedNFT: true,

    isWeb3: true,
    isFee: true,
    icon: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche C-Chain',
    shortName: 'Avalanche',
    logo: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: CHAIN_TYPE.avax,
    tokenStandard: 'AVAX-C ARC20',
    rpcURL: 'https://avalanche-mainnet.core.chainstack.com/ext/bc/C/rpc/9b468d696721b81f0d1feaa43964b4aa',
    scan: 'https://snowscan.xyz',
  },
  avaxX: {
    order: 5,
    isToken: true,
    replacementSymbol: 'XCHAIN',
    subName: 'X',
    icon: 'app_avalancher',
    id: 'avalanche-2',
    name: 'Avalanche X-Chain',
    shortName: 'Avalanche',
    logo: COIN_IMAGE.AVAX,
    symbol: 'AVAX',
    chain: CHAIN_TYPE.avaxX,
    tokenStandard: 'AVAX-X',
    scan: 'https://avascan.info/blockchain/x',
  },
  tron: {
    order: 1,
    isToken: true,
    standard: 'TRC20',
    subName: 'TRC10',
    icon: 'app_tron',
    id: 'tron',
    name: 'Tron',
    shortName: 'Tron',
    logo: COIN_IMAGE.TRX,
    symbol: 'TRX',
    chain: CHAIN_TYPE.tron,
    tokenStandard: 'TRX TRC10 TRC20',
    scan: 'https://tronscan.org/#',
    scanTxPrefix: 'transaction',
  },
  matic: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    isDataField: true,
    numChainId: 137,
    chainId: '0x89',
    order: 2,
    isToken: true,
    standard: 'PRC20',
    nftStandard: 'PRC721',
    isFee: true,
    isWeb3: true,
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0x555Bf8AE336910615d9b965aEE8c5A3fA06B9ddD',
    // //nftMint: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',

    isSupportedNFT: true,
    id: 'matic-network',
    name: 'Polygon',
    icon: 'app_polygon',
    logo: COIN_IMAGE.MATIC,
    symbol: 'POL',
    chain: CHAIN_TYPE.matic,
    tokenStandard: 'POL PRC20',
    rpcURL: 'https://polygon-mainnet.core.chainstack.com/820dd6cca00bc68326ce2eecf3043138',
    scan: 'https://polygonscan.com',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  metis: {
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    id: 'metis-token',
    isToken: true,
    numChainId: 1088,
    chainId: '0x440',
    standard: 'MRC20',
    nftStandard: 'MRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_metis',
    name: 'Metis ',
    shortName: 'METIS',
    symbol: 'METIS',
    chain: CHAIN_TYPE.metis,
    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://andromeda.metis.io/?owner=1088',
    scan: 'https://andromeda-explorer.metis.io',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  blast: {
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    id: 'ethereum',
    replacementSymbol: 'BLAST',
    isToken: true,
    isL2: true,
    numChainId: 81457,
    chainId: '0x13E31',
    standard: 'BRC20',
    nftStandard: 'BRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_blast',
    name: 'Blast',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.blast,
    tokenStandard: 'BRC20 BRC721',
    rpcURL: 'https://rpc.blast.io',
    scan: 'https://blastscan.io',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  mode: {
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    id: 'ethereum',
    replacementSymbol: 'MODE',
    isToken: true,
    isL2: true,
    numChainId: 34443,
    chainId: '0x868b',
    standard: 'MRC20',
    nftStandard: 'MRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_mode',
    name: 'Mode',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.mode,
    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://mainnet.mode.network',
    scan: 'https://explorer.mode.network',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  zora: {
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    id: 'ethereum',
    replacementSymbol: 'ZORA',
    isToken: true,
    isL2: true,
    numChainId: 7777777,
    chainId: '0x76adf1',
    standard: 'ZRC20',
    nftStandard: 'ZRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_zora',
    name: 'Zora',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.zora,
    tokenStandard: 'ZRC20 ZRC721',
    rpcURL: 'https://rpc.zora.energy',
    scan: 'https://explorer.zora.energy',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  fantom: {
    isCrawlNFTServices: true,
    isCrawlServices: true,
    numChainId: 250,
    chainId: '0xfa',
    order: 2,
    isToken: true,
    standard: 'FRC20',
    nftStandard: 'FRC721',
    balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    multiTransferContract: '0xC285B7E09A4584D027E5BC36571785B515898246',
    // //nftMint: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    isFee: true,
    isWeb3: true,
    isSupportedNFT: true,
    isSupportedV2: true,
    id: 'fantom',
    name: 'Fantom',
    icon: 'app_fantom',
    logo: COIN_IMAGE.FTM,
    symbol: 'FTM',
    chain: CHAIN_TYPE.fantom,
    tokenStandard: 'FTM FRC20',
    rpcURL: "https://fantom-mainnet.core.chainstack.com/d057ecc240cc06a2ae65550faf51e34b",
    scan: 'https://ftmscan.com',
  },
  xDai: {
    // isSupportedEIP1559: true,
    numChainId: 100,
    chainId: '0x64',
    order: 2,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    // //nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',
    isToken: true,
    id: 'xdai',
    isSupportedNFT: true,
    name: 'Gnosis Chain',
    icon: 'app_xDai',
    symbol: 'XDAI',
    chain: CHAIN_TYPE.xDai,
    logo: COIN_IMAGE.XDAI,
    standard: 'XRC20',
    nftStandard: 'XRC721',
    tokenStandard: 'XDAI XRC20',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://rpc.gnosischain.com/',
    scan: 'https://blockscout.com/xdai/mainnet',
  },
  polkadot: {
    order: 3,
    icon: 'app_polkadot',
    isMnemonicOnly: true,
    id: 'polkadot',
    name: 'Polkadot',
    shortName: 'Polkadot',
    logo: COIN_IMAGE.DOT,
    symbol: 'DOT',
    chain: CHAIN_TYPE.polkadot,
    tokenStandard: 'DOT',
    rpcURL: 'rpc.polkadot.io',
    scan: 'https://polkadot.subscan.io',
    scanTxPrefix: 'extrinsic',
    scanAddressPrefix: 'account',
  },
  kusama: {
    order: 3,
    icon: 'app_kusama',

    isMnemonicOnly: true,
    id: 'kusama',
    name: 'Kusama',
    shortName: 'Kusama',
    logo: COIN_IMAGE.KSM,
    symbol: 'KSM',
    chain: CHAIN_TYPE.kusama,
    tokenStandard: 'KSM',
    rpcURL: 'kusama-rpc.polkadot.io',
    scan: 'https://kusama.subscan.io',
    scanTxPrefix: 'extrinsic',
  },
  cosmos: {
    prefix: 'cosmos',
    path: 118,

    order: 3,
    isFactory: true,
    isCosmos: true,
    isMemo: true,
    id: 'cosmos',
    chainId: 'cosmoshub-4',
    name: 'Cosmos',
    icon: 'app_cosmos',
    symbol: 'ATOM',
    logo: COIN_IMAGE.ATOM,
    chain: CHAIN_TYPE.cosmos,
    tokenStandard: 'ATOM',
    scan: 'https://www.mintscan.io/cosmos',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'blocks/id',
  },
  thor: {
    prefix: 'thor',
    path: 931,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    id: 'thorchain',
    chainId: 'thorchain-mainnet-v1',
    name: 'THORChain',
    icon: 'app_thorchain',
    logo: COIN_IMAGE.RUNE,
    symbol: 'RUNE',
    chain: CHAIN_TYPE.thor,
    tokenStandard: 'RUNE',
    scan: 'https://viewblock.io/thorchain',
    standard: 'RUNE',
  },
  aura: {
    prefix: 'aura',
    path: 118,
    nftStandard: 'CW721',

    // numLoad: 1,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: true,
    isSupportedNFT: true,
    // isDynamic: true,

    chainId: 'aura_6322-2',
    id: 'aura-network',
    name: 'Aura Xstaxy Mainnet',
    icon: 'app_aura_network',
    symbol: 'AURA',
    logo: COIN_IMAGE.AURA,
    chain: CHAIN_TYPE.aura,
    subName: 'AURA CW-20 CW-721',
    scan: 'https://aurascan.io',
    rpcURL: 'https://rpc.aura.network',
    // rest: 'https://lcd.aura.network',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  terra: {
    prefix: 'terra',
    path: 330,
    order: 3,
    isToken: true,
    standard: 'CW20',
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'terra-luna',
    name: 'Old Terra',
    icon: 'app_terra',
    symbol: 'LUNC',
    logo: COIN_IMAGE.LUNA,
    chain: CHAIN_TYPE.terra,
    tokenStandard: 'LUNC CW20',
    chainId: 'columbus-5',
    scan: 'https://finder.terra.money/columbus-5',
  },

  kava: {
    prefix: 'kava',
    path: 459,
    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    id: 'kava',
    name: 'Kava',
    chainId: 'kava_2222-10',
    icon: 'app_kava',
    logo: COIN_IMAGE.KAVA,
    symbol: 'KAVA',
    chain: CHAIN_TYPE.kava,
    tokenStandard: 'KAVA',
    scan: 'https://www.mintscan.io/kava',
    rpcURL: 'https://kava4.data.kava.io',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'blocks/id',
  },

  secretNetwork: {
    prefix: 'secret',
    path: 529,

    order: 3,
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'secret',
    chainId: 'secret-4',
    name: 'Secret Network',
    icon: 'app_secret_network',
    logo: COIN_IMAGE.SCRT,
    symbol: 'SCRT',
    chain: CHAIN_TYPE.secretNetwork,
    tokenStandard: 'SCRT',
    rpcURL: 'https://api.secretapi.io',
    scan: 'https://www.mintscan.io/secret',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'blocks/id',
  },

  persistence: {
    prefix: 'persistence',
    path: 750,

    order: 3,
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'persistence',
    chainId: 'core-1',
    name: 'Persistence',
    icon: 'app_persistence',
    logo: COIN_IMAGE.XPRT,
    symbol: 'XPRT',
    chain: CHAIN_TYPE.persistence,
    tokenStandard: 'XPRT',
    scan: 'https://www.mintscan.io/persistence',
    scanBlockPrefix: 'blocks',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'accounts',
  },
  functionX: {
    prefix: 'fx',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,

    chainId: 'fxcore',
    id: 'fx-coin',
    name: 'f(x) Core',
    icon: 'app_functionX',
    symbol: 'FX',
    logo: COIN_IMAGE.FX,
    chain: CHAIN_TYPE.functionX,
    tokenStandard: 'FX FXRC20',
    scan: 'https://explorer.functionx.io/fxcore',
    rpcURL: 'https://fx-json.functionx.io:26657',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },

  functionXEVM: {
    prefix: 'fx',
    numChainId: 530,
    chainId: '0x212',
    order: 3,
    isWeb3: true,
    isFee: true,
    id: 'fx-coin',
    name: 'f(x) Core EVM',
    symbol: 'FX',
    icon: 'app_functionX',
    chain: CHAIN_TYPE.functionXEVM,
    tokenStandard: 'FX FXRC20',
    standard: 'FXRC20',
    scan: 'https://starscan.io/evm',
    rpcURL: 'https://fx-json-web3.functionx.io:8545',
    replacementSymbol: 'EVM'
  },

  elrond: {
    isLibrary: true,

    prefix: 'erd',
    path: 508,
    nftStandard: 'SFT',
    order: 3,
    defaultFee: 0.00005,
    isToken: true,
    standard: 'ESDT',

    id: 'elrond-erd-2',
    name: 'MultiversX',
    icon: 'app_multiversx',
    logo: COIN_IMAGE.EGLD,
    symbol: 'EGLD',
    chain: CHAIN_TYPE.elrond,
    tokenStandard: 'EGLD ESDT SFT',
    scan: 'https://explorer.multiversx.com',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'accounts',
    scanBlockPrefix: 'blocks',
    rpcURL: 'https://api.elrond.com/'
  },
  tezos: {
    isLibrary: true,
    defaultFee: 0.0015,

    prefix: 'tz1',
    path: 1729,
    nftStandard: 'FA2',
    isToken: true,
    standard: 'FA1.2',
    order: 2,

    id: 'tezos',
    name: 'Tezos',
    icon: 'app_tezos',
    logo: COIN_IMAGE.XTZ,
    symbol: 'XTZ',
    chain: CHAIN_TYPE.tezos,
    tokenStandard: 'XTZ FA1.2 FA2',
    scan: 'https://tezblock.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
    scanBlockPrefix: 'block',
  },
  celo: {
    // mainAddress: '0x471ece3750da237f93b8e339c536989b8978a438',
    path: 52752,
    isFee: true,
    numChainId: 42220,
    chainId: '0xA4EC',
    order: 1,
    isSupportedNFT: true,
    isToken: true,
    balanceContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isWeb3: true,
    icon: 'app_celo',
    id: 'celo',
    name: 'Celo',
    shortName: 'Celo',
    logo: COIN_IMAGE.CELO,
    symbol: 'CELO',
    chain: CHAIN_TYPE.celo,
    tokenStandard: 'CELO CUSD',
    nftStandard: 'CELO721',
    rpcURL: 'https://forno.celo.org',
    scan: 'https://explorer.celo.org',
  },
  tomo: {
    path: 889,

    numChainId: 88,
    chainId: '0x58',
    // isCrawlServices: true,

    order: 2,
    isToken: true,
    standard: 'VRC25',
    nftStandard: 'VRC721',
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    // nftMint: '0xAE12C5930881c53715B369ceC7606B70d8EB229f',

    isWeb3: true,
    isFee: true,
    icon: 'app_viction',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x3c39f41b6d7ee19F8e3aC4Df886f595736029b20',
    // multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',

    id: 'tomochain',
    name: 'Viction',
    shortName: 'Vic',
    logo: COIN_IMAGE.TOMO,
    symbol: 'VIC',
    chain: CHAIN_TYPE.tomo,
    tokenStandard: 'VIC VRC25',
    rpcURL: 'https://rpc5.viction.xyz',
    scan: 'https://www.vicscan.xyz'
  },
  victionTestnet: {
    environment: 'testnet',
    numChainId: 89,
    chainId: '0x59',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'VRC25 Testnet',
    nftStandard: 'VRC725 Testnet',
    isWeb3: true,
    isFee: true,
    icon: 'app_viction',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    name: 'Viction Testnet',
    shortName: 'VIC',
    logo: COIN_IMAGE.TOMO,
    symbol: 'VIC',
    chain: CHAIN_TYPE.victionTestnet,
    tokenStandard: 'VIC VRC25',
    rpcURL: 'https://rpc-testnet.viction.xyz',
    scan: 'https://testnet.vicscan.xyz',
  },
  algorand: {
    defaultFee: 0.001,
    standard: 'ALGO',
    nftStandard: 'ALGO721',
    isToken: true,
    id: 'algorand',
    name: 'Algorand',
    icon: 'app_algorand',
    logo: COIN_IMAGE.ALGO,
    symbol: 'ALGO',
    chain: CHAIN_TYPE.algorand,
    tokenStandard: 'ALGO ALGO721',
    scan: 'https://allo.info/',
  },
  algorandTestnet: {
    environment: 'testnet',
    defaultFee: 0.001,
    standard: 'ALGO',
    nftStandard: 'ALGO721',
    isToken: true,
    id: 'algorand',
    name: 'Algorand Testnet',
    icon: 'app_algorand',
    logo: COIN_IMAGE.ALGO,
    symbol: 'ALGO',
    chain: CHAIN_TYPE.algorandTestnet,
    tokenStandard: 'ALGO ALGO721',
    scan: 'https://testnet.explorer.perawallet.app/',
  },
  casper: {
    standard: 'CSPR',
    nftStandard: 'CSPR-NFT',
    id: 'casper-network',
    name: 'Casper',
    icon: 'app_casper',
    logo: COIN_IMAGE.CSPR,
    symbol: 'CSPR',
    chain: CHAIN_TYPE.casper,
    tokenStandard: 'CSPR',
    scanTxPrefix: 'deploy',
    scanAddressPrefix: 'account',
    scan: 'https://cspr.live',
    isMemo: true,
  },

  kardia: {
    numChainId: 24,
    chainId: '0x18',

    order: 2,
    isToken: true,
    isDataField: true,
    id: 'kardiachain',
    name: 'KardiaChain',
    icon: 'app_kardia',
    symbol: 'KAI',
    chain: CHAIN_TYPE.kardia,
    logo: COIN_IMAGE.KAI,
    subName: 'KAI',
    standard: 'KRC20',
    nftStandard: 'KRC721',
    tokenStandard: 'KAI KRC20 KRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://rpc.kardiachain.io',
    scan: 'https://explorer.kardiachain.io',

    balanceContract: '0x8ef3C4Bf105Ec17cbeD7615C5711d2F4D44a4194',
    multiTransferContract: '0xf21201135568A81c9046d60a003eC2B883173F2f',
    // nftMint: '0x8347CD0aaF874259e9d577BeE08231F648C3fc29'
  },
  ronin: {
    prefix: 'ronin:',
    numChainId: 2020,
    chainId: '0x7e4',

    order: 2,
    isSupportedNFT: true,
    isCrawlServices: true,
    isToken: true,
    id: 'ronin',
    name: 'Ronin',
    icon: 'app_ronin',
    nftStandard: 'RRC721',
    symbol: 'RON',
    chain: CHAIN_TYPE.ronin,
    logo: COIN_IMAGE.RON,
    standard: 'RRC20',
    tokenStandard: 'RON RRC20 RRC721',
    isFee: true,
    isWeb3: true,
    rpcURL: 'https://api.roninchain.com/rpc',
    scan: 'https://explorer.roninchain.com',
  },

  klaytn: {
    numChainId: 8217,
    chainId: '0x2019',

    order: 2,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5c93f4b35d3dd97ef481881aa33d00f76806fdad',

    isSupportedNFT: true,
    isToken: true,
    id: 'klay-token',
    name: 'Klaytn',
    icon: 'app_klaytn',
    symbol: 'KLAY',
    standard: 'KIP7',
    nftStandard: 'KIP37',

    chain: CHAIN_TYPE.klaytn,
    logo: COIN_IMAGE.KLAY,
    tokenStandard: 'KLAY KIP7 KIP37',
    isFee: true,
    isWeb3: true,
    scan: 'https://scope.klaytn.com',
    rpcURL: 'https://public-en.node.kaia.io',
    scanAddressPrefix: 'account',
  },
  //
  harmony: {
    prefix: 'one',
    numChainId: 1666600000,
    chainId: '0x63564C40',
    order: 1,
    isDataField: true,
    isToken: true,
    isSupportedNFT: true,
    nftStandard: 'HRC721',
    standard: 'HRC20',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',
    // nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    isWeb3: true,
    isFee: true,
    icon: 'app_harmony',

    id: 'harmony',
    name: 'Harmony',
    logo: COIN_IMAGE.ONE,
    symbol: 'ONE',
    chain: CHAIN_TYPE.harmony,
    tokenStandard: 'ONE HRC20 HRC721',
    rpcURL: 'https://api.harmony.one',
    scan: 'https://explorer.harmony.one',
  },

  conflux: {
    isLibrary: true,
    defaultFee: 0.00005,

    prefix: 'cfx',
    standard: 'CRC20',
    nftStandard: 'CRC721',
    isToken: true,
    order: 100,

    id: 'conflux-token',
    name: 'Conflux Core Space',
    icon: 'app_conflux',
    logo: COIN_IMAGE.CFX,
    symbol: 'CFX',
    chain: CHAIN_TYPE.conflux,
    tokenStandard: 'CFX CRC20 CRC721',
    scan: 'https://www.confluxscan.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'address',
    scanBlockPrefix: 'block',
  },
  optimism: {
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    isCrawlServices: true,
    // defaultFee: 882000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    numChainId: 10,
    chainId: '0xa',
    rapidNetwork: true,
    // numChainId: 69,
    // chainId: '0x45',

    order: 2,
    isToken: true,
    standard: 'ERC20 OP',
    nftStandard: 'ERC721 OPT',
    balanceContract: '0xA6762c710852681c4593C10c4304C5211FB2122c',
    multiTransferContract: '0xD53625c76A32883d683bF56e28796f7eB78C9AA0',
    isWeb3: true,
    isFee: true,
    icon: 'app_optimism',
    id: 'ethereum',
    name: 'Optimism',
    shortName: 'Optimism',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    replacementSymbol: 'OP',
    chain: CHAIN_TYPE.optimism,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://optimism-mainnet.core.chainstack.com/cdd048b0e809173f747bcab2727e0a6f',
    scan: 'https://optimistic.etherscan.io',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  boba: {
    // defaultFee: 80000000,
    // mainAddress: '0x4200000000000000000000000000000000000006',
    isL2: true,
    numChainId: 288,
    chainId: '0x120',

    order: 2,
    isToken: true,
    standard: 'ERC20 BOBA',
    nftStandard: 'ERC721 BOBA',
    // multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
    isWeb3: true,
    isFee: true,
    icon: 'app_boba',
    id: 'ethereum',
    name: 'Boba Network',
    shortName: 'Boba Network',
    logo: COIN_IMAGE.BOBA,
    symbol: 'ETH',
    replacementSymbol: 'BOBA',
    chain: CHAIN_TYPE.boba,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.boba.network',
    scan: 'https://bobascan.com',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  zkSyncPolygon: {
    numChainId: 1101,
    chainId: '0x44D',
    isToken: true,
    isDataField: true,
    isSupportedNFT: true,
    standard: 'zkPolgon ERC20',
    nftStandard: 'ERC721',
    balanceContract: '0x8bfcbf5cbb6729c11ccb2949C149D8928b6C932C',
    multiTransferContract: '0xafb9013228D365AcEE408543B284240F7965EDDD',
    // nftMint: '0x8437BF9557eE3a32e964a8Ff300DF69379d747a4',
    isWeb3: true,
    isFee: true,
    icon: 'app_zk_polygon',
    id: 'ethereum',
    name: 'Polygon zkEVM',
    shortName: 'Polygon zkEVM',
    replacementSymbol: 'zkPolygon',
    // replacementSymbol: 'zkPolygon',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.zkSyncPolygon,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://zkevm-rpc.com',
    scan: 'https://zkevm.polygonscan.com',
  },
  zkSyncEra: {
    numChainId: 324,
    chainId: '0x144',
    // numLoad: 2,
    isToken: true,
    isDataField: true,
    standard: 'zkEra ERC20',
    nftStandard: 'zeERC721',
    isFee: true,
    isWeb3: true,
    balanceContract: '0x71C51F41AC11A474bA53972cDbaA74f7BECE9023',
    // multisend: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    // nftMint: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    id: 'ethereum',
    name: 'zkSync Era',
    icon: 'app_zk_era',
    logo: COIN_IMAGE.ETH,
    replacementSymbol: 'zkEra',
    symbol: 'ETH',
    chain: CHAIN_TYPE.zkSyncEra,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://mainnet.era.zksync.io',
    scan: 'https://explorer.zksync.io/',
  },
  arbitrum: {
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    isCrawlServices: true,
    defaultFee: 7000000,
    isL2: true,
    numChainId: 42161,
    chainId: '0xa4b1',
    rapidNetwork: true,
    // numChainId: 421611,
    // chainId: '0x66EEB',

    order: 2,
    isToken: true,
    standard: 'ERC20 ARB',
    nftStandard: 'ERC721 ARB',
    balanceContract: '0x836bf46520C373Fdc4dc7E5A3bAe735d13bD44e3',
    multiTransferContract: '0xe832acd32F9f4535e7295c8728EBbb4D46FC205F',
    isWeb3: true,
    isFee: true,
    icon: 'app_arbitrum',
    id: 'ethereum',
    name: 'Arbitrum',
    shortName: 'Arbitrum',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    replacementSymbol: 'ARB',
    chain: CHAIN_TYPE.arbitrum,
    tokenStandard: 'ETH ERC20 ERC721',
    rpcURL: 'https://arbitrum-mainnet.core.chainstack.com/0341cac807a3d866f93bfec3b8786c46',
    // rpcURL: 'https://rinkeby.arbitrum.io/rpc',
    scan: 'https://arbiscan.io',
    // nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC'
  },
  // arbitrumXdai: {
  //   isL2: true,
  //   numChainId: 200,
  //   chainId: '0xC8',

  //   order: 2,
  //   isSupportedNFT: true,
  //   isToken: true,
  //   standard: 'ERC20 AOX',
  //   nftStandard: 'ERC721 AOX',
  //   balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  //   multiTransferContract: '0x3c39f41b6d7ee19F8e3aC4Df886f595736029b20',
  //   // nftMint: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
  //   isWeb3: true,
  //   isFee: true,
  //   icon: 'app_arbitrum_xdai',
  //   id: 'xdai',
  //   name: 'Arbitrum on xDai',
  //   shortName: 'Arbitrum on xDai',
  //   logo: COIN_IMAGE.ETHA0X,
  //   symbol: 'XDAI',
  //   replacementSymbol: 'AOX',
  //   chain: CHAIN_TYPE.arbitrumXdai,
  //   tokenStandard: 'XDAI XRC20 XRC721',
  //   rpcURL: 'https://arbitrum.xdaichain.com',
  //   scan: 'https://blockscout.com/xdai/aox'
  // },

  aurora: {
    isL2: true,
    defaultFee: 0,

    numChainId: 1313161554,
    chainId: '0x4e454152',
    order: 2,
    isToken: true,
    isDataField: true,
    isSupportedNFT: true,
    nftStandard: 'AURORA721',
    standard: 'AURORA20',
    balanceContract: '0xbaeBE441F490dAC97106Ec9390504F0B1bb2Ea54',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // //nftMint: '0xc4cAd0938256ABA4417c565044Be2c2EB77096cb',

    isWeb3: true,
    icon: 'app_aurora',

    id: 'aurora-near',
    name: 'Aurora',
    shortName: 'Aurora',
    logo: COIN_IMAGE.AURORA,
    symbol: 'AURORA ETH',
    chain: CHAIN_TYPE.aurora,
    tokenStandard: 'AURORA AURORA20 AURORA721',
    rpcURL: 'https://aurora-mainnet.core.chainstack.com/863f618d49f8d2dfecfed48c8d74a374',
    scan: 'https://explorer.mainnet.aurora.dev',
  },
  ton: {
    id: 'the-open-network',
    name: 'The Open Network',
    shortName: 'TON',
    logo: COIN_IMAGE.TON,
    isToken: false,
    isMemo: true,
    symbol: 'TON',
    chain: CHAIN_TYPE.ton,
    tokenStandard: 'TON TON721',
    rpcURL: 'https://toncenter.com/api/v2/jsonRPC',
    scan: 'https://tonviewer.com/',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: '',
    icon: 'app_ton',
  },

  // ? Recent release
  cronos: {
    id: 'crypto-com-chain',
    chain: CHAIN_TYPE.cronos,
    name: 'Cronos',
    shortName: 'CRO',
    isToken: true,
    standard: 'CRO',
    numChainId: 25,
    chainId: '0x19',
    symbol: 'CRO',
    icon: 'app_cronos',
    tokenStandard: 'CRC20 CRC721',
    rpcURL: 'https://evm-cronos.crypto.org',
    scan: 'https://cronoscan.com',
    logo: COIN_IMAGE.CRO,
    // isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // nftMint: '0x3c39f41b6d7ee19F8e3aC4Df886f595736029b20',
    multiTransferContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
  },
  bittorrent: {
    numChainId: 199,
    chainId: '0xc7',
    isToken: true,
    standard: 'BTT',
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'bittorrent',
    name: 'BitTorrent Chain',
    shortName: 'BTT',
    icon: 'app_bitorrent',
    logo: COIN_IMAGE.BTT,
    symbol: 'BTT',
    chain: CHAIN_TYPE.bittorrent,
    tokenStandard: 'BTT BRC20 BRC721',
    balanceContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    // nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    rpcURL: 'https://rpc.bt.io',
    scan: 'https://scan.bt.io/#',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'address',
  },
  theta: {
    standard: 'THETA',
    id: 'theta-token',
    name: 'Theta Network',
    shortName: 'THETA',
    icon: 'app_thetanetwork',
    logo: COIN_IMAGE.THETA,
    symbol: 'THETA',
    chain: CHAIN_TYPE.theta,
    tokenStandard: 'TNT20 TNT721',
    rpcURL: 'https://theta-bridge-rpc.thetatoken.org/rpc',
    scan: 'https://explorer.thetatoken.org',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    // isFee: true
  },
  thetaFuel: {
    numChainId: 361,
    chainId: '0x169',
    isToken: true,
    standard: 'TFUEL',
    isSupportedNFT: true,
    isDataField: true,
    isWeb3: true,
    isFee: true,
    id: 'theta-fuel',
    name: 'Theta Network EVM',
    shortName: 'THETA',
    icon: 'app_thetanetwork',
    logo: COIN_IMAGE.TFUEL,
    symbol: 'TFUEL',
    chain: CHAIN_TYPE.thetaFuel,
    tokenStandard: 'TNT20 TNT721',
    rpcURL: 'https://eth-rpc-api.thetatoken.org/rpc',
    scan: 'https://explorer.thetatoken.org',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    balanceContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    // nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0xf7eee3a8363731c611a24cddfcbcade9c153cfe8',
  },
  platon: {
    id: 'platon-network',
    numChainId: 210425,
    chainId: '0x335F9',
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'LAT',
    name: 'PlatON Network',
    shortName: 'LAT',
    icon: 'app_platon',
    logo: COIN_IMAGE.LAT,
    symbol: 'LAT',
    chain: CHAIN_TYPE.platon,
    prefix: 'lat',

    tokenStandard: 'PRC20 PRC721',
    rpcURL: 'https://openapi2.platon.network/rpc',
    scan: 'https://scan.platon.network',
    // multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // balanceContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    // //nftMint: '0x3c39f41b6d7ee19F8e3aC4Df886f595736029b20',
    multiTransferContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isDataField: true
  },
  moonbeam: {
    numChainId: 1284,
    chainId: '0x504',
    isToken: true,
    standard: 'GLMR',
    isSupportedEIP1559: true,
    isSupportedNFT: true,
    isWeb3: true,
    isFee: true,
    id: 'moonbeam',
    name: 'Moonbeam',
    shortName: 'GLMR',
    icon: 'app_moonbeam',
    logo: COIN_IMAGE.GLMR,
    symbol: 'GLMR',
    chain: CHAIN_TYPE.moonbeam,
    tokenStandard: 'MERC20 MERC721',
    rpcURL: 'https://rpc.api.moonbeam.network',
    scan: 'https://moonscan.io',
    balanceContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    // //nftMint: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  },
  aptosLabs: {
    environment: 'mainnet',
    chainId: 'aptoslabs',
    // isToken: true,
    standard: 'APT',
    id: 'aptos',
    name: 'Aptos',
    shortName: 'APT',
    icon: 'app_aptos',
    logo: COIN_IMAGE.APT,
    symbol: 'APT',
    chain: CHAIN_TYPE.aptosLabs,
    tokenStandard: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.mainnet.aptoslabs.com',
    scan: 'https://tracemove.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
  },
  injective: {
    prefix: 'inj',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'injective-1',
    id: 'injective-protocol',
    name: 'Injective',
    icon: 'app_injective',
    symbol: 'INJ',
    logo: COIN_IMAGE.INJ,
    chain: CHAIN_TYPE.injective,
    tokenStandard: 'INJ',
    scan: 'https://www.mintscan.io/injective',
    rpcURL: 'https://injective-rpc.publicnode.com:443',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
    isSupportedNFT: true,
    isCrawlNFTServices: true,
  },
  osmosis: {
    prefix: 'osmo',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'osmosis-1',
    id: 'osmosis',
    name: 'Osmosis',
    icon: 'app_omosis',
    symbol: 'OSMO',
    logo: COIN_IMAGE.OSMO,
    chain: CHAIN_TYPE.osmosis,
    tokenStandard: 'OSMO',
    scan: 'https://www.mintscan.io/osmosis',
    rpcURL: 'https://rpc-osmosis.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  evmos: {
    prefix: 'evmos',
    path: 60,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'evmos_9001-2',
    id: 'evmos',
    name: 'Evmos',
    icon: 'app_evmos',
    symbol: 'EVMOS',
    logo: COIN_IMAGE.EVMOS,
    chain: CHAIN_TYPE.evmos,
    tokenStandard: 'EVMOS',
    scan: 'https://www.mintscan.io/evmos',
    rpcURL: 'https://rpc-evmos.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  juno: {
    prefix: 'juno',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'juno-1',
    id: 'juno-network',
    name: 'Juno Network',
    icon: 'app_juno',
    symbol: 'JUNO',
    logo: COIN_IMAGE.JUNO,
    chain: CHAIN_TYPE.juno,
    tokenStandard: 'JUNO',
    scan: 'https://www.mintscan.io/juno',
    rpcURL: 'https://rpc-osmosis.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },

  agoric: {
    prefix: 'agoric',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'agoric-3',
    id: 'agoric',
    name: 'Agoric',
    icon: 'app_agoric',
    symbol: 'BLD',
    logo: COIN_IMAGE.BLD,
    chain: CHAIN_TYPE.agoric,
    tokenStandard: 'BLD',
    scan: 'https://agoric.explorers.guru/',
    rpcURL: 'https://rpc-agoric.keplr.app',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
  },
  // kaneda: {},
  oasis: {
    numChainId: 42262,
    chainId: '0xa516',
    order: 0,
    isToken: true,

    standard: 'ORC20',
    nftStandard: 'ORC721',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',

    isWeb3: true,
    isFee: true,
    icon: 'app_oasis',
    id: 'oasis-network',
    name: 'Oasis Network',
    shortName: 'ROSE',
    logo: COIN_IMAGE.ROSE,
    symbol: 'ROSE',
    chain: CHAIN_TYPE.oasis,
    tokenStandard: 'ROSE ORC20 ORC721',
    rpcURL: 'https://emerald.oasis.dev',
    scan: 'https://explorer.oasis.io/mainnet/emerald/',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  kujira: {
    prefix: 'kujira',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'kaiyo-1',
    id: 'kujira',
    name: 'Kujira',
    icon: 'app_kujira',
    symbol: 'KUJI',
    logo: COIN_IMAGE.KUJI,
    chain: CHAIN_TYPE.kujira,
    tokenStandard: 'KUJI',
    scan: ' https://finder.kujira.network/kaiyo-1',
    rpcURL: 'https://rpc.kaiyo.kujira.setten.io',
    // scanTxPrefix: 'tx',
    // scanAddressPrefix: 'account'
  },
  stargaze: {
    prefix: 'stars',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'stargaze-1',
    id: 'stargaze',
    name: 'Stargaze',
    icon: 'app_stagraze',
    symbol: 'STARS',
    logo: COIN_IMAGE.STARS,
    chain: CHAIN_TYPE.stargaze,
    tokenStandard: 'STARS',
    scan: 'https://www.mintscan.io/stargaze',
    rpcURL: 'https://rpc-stargaze.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  umee: {
    prefix: 'umee',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'umee-1',
    id: 'umee',
    name: 'Umee',
    icon: 'app_umee',
    symbol: 'UMEE',
    logo: COIN_IMAGE.UMEE,
    chain: CHAIN_TYPE.umee,
    tokenStandard: 'UMEE',
    scan: 'https://www.mintscan.io/umee',
    rpcURL: 'https://rpc-umee.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  stride: {
    prefix: 'stride',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,

    chainId: 'stride-1',
    id: 'stride',
    name: 'Stride',
    icon: 'app_stride',
    symbol: 'STRD',
    logo: COIN_IMAGE.STRD,
    chain: CHAIN_TYPE.stride,
    tokenStandard: 'STRD',
    scan: 'https://www.mintscan.io/stride',
    rpcURL: 'https://rpc-stride.keplr.app',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  baseTest: {
    isToken: true,
    isSupportedNFT: true,

    tokenStandard: 'ETH ERC20 ERC721',
    nftStandard: 'ERC721',
    standard: 'ERC20 BASE',
    environment: 'devnet',
    // isDevnet: true,
    numChainId: 84531,
    chainId: '0x14A33',
    // numLoad: 2,
    isFee: true,
    isWeb3: true,
    balanceContract: '0x1C40CBda91e1E0504805eCf038F2e067D11DdBE9',
    multiTransferContract: '0x8a77C6d87B5E5Ea7e779C7d14cA50315Bfc4C019',
    name: 'Base Testnet',
    icon: 'app_base',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.baseTest,
    rpcURL: 'https://base-goerli.public.blastapi.io',
    scan: 'https://goerli.basescan.org',
    replacementSymbol: 'BASE TESTNET',

    id: 'base-test',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  base: {
    isToken: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,

    tokenStandard: 'ETH ERC20 ERC721',
    nftStandard: 'ERC721',
    standard: 'ERC20 BASE',
    // environment: 'devnet',
    // isDevnet: true,
    numChainId: 8453,
    chainId: '0x2105',
    // numLoad: 2,
    isFee: true,
    isWeb3: true,
    balanceContract: '0x603873414d44a199AB25eDdD0bfBa96C62f8537D',
    name: 'Base',
    icon: 'app_base',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.base,
    rpcURL: 'https://base-mainnet.core.chainstack.com/a5be7e938ebdf6b5040f9c0623a0a07d',
    scan: 'https://basescan.org',
    id: 'ethereum',
    replacementSymbol: 'BASE',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  aptos: {
    environment: 'testnet',
    // isDevnet: true,
    chainId: 'ait-3',
    standard: 'APT',
    id: 'aptos-test',
    name: 'Aptos Testnet',
    shortName: 'APT',
    icon: 'app_aptos',
    logo: COIN_IMAGE.APT,
    symbol: 'APT',
    chain: CHAIN_TYPE.aptos,
    tokenStandard: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.testnet.aptoslabs.com',
    scan: 'https://testnet.tracemove.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
    nameSuffix: 'Testnet',
    symbolSuffix: 'TEST',
  },

  aptosDev: {
    environment: 'devnet',
    // isDevnet: true,
    chainId: 'ait-dev',
    standard: 'APT',
    id: 'aptos-dev',
    name: 'Aptos Devnet',
    shortName: 'APT',
    icon: 'app_aptos',
    logo: COIN_IMAGE.APT,
    symbol: 'APT',
    chain: CHAIN_TYPE.aptosDev,
    tokenStandard: 'APTOS AIT-3',
    rpcURL: 'https://fullnode.devnet.aptoslabs.com',
    scan: 'https://devnet.tracemove.io',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'account',
    nameSuffix: 'Devnet',
    symbolSuffix: 'DEV',
  },
  // sui: {
  //   environment: 'devnet',
  //   chainId: 'sui',
  //   standard: 'SUI',
  //   id: 'sui',
  //   name: 'Sui Testnet',
  //   shortName: 'Sui',
  //   icon: 'app_sui',
  //   logo: COIN_IMAGE.SUI,
  //   symbol: 'SUI',
  //   chain: CHAIN_TYPE.sui,
  //   tokenStandard: 'SUI',
  //   rpcURL: 'https://gateway.devnet.sui.io:443',
  //   scan: 'https://explorer.devnet.sui.io',
  //   scanTxPrefix: 'transactions',
  //   scanAddressPrefix: 'addresses'
  // },
  suiMainnet: {
    chainId: 'sui',
    tokenStandard: 'SUI',
    id: 'sui',
    name: 'Sui',
    shortName: 'Sui',
    icon: 'app_sui',
    logo: COIN_IMAGE.SUI,
    symbol: 'SUI',
    chain: CHAIN_TYPE.suiMainnet,
    standard: 'SUI',
    rpcURL: 'https://wallet-rpc.mainnet.sui.io/',
    scan: 'https://suiscan.xyz/mainnet',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'account',
  },
  sei: {
    environment: 'testnet',
    prefix: 'sei',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: true,
    isSupportedNFT: true,

    chainId: 'atlantic-2',
    id: 'sei',
    name: 'Sei Testnet',
    icon: 'app_sei',
    symbol: 'SEI',
    logo: COIN_IMAGE.SEI,
    chain: CHAIN_TYPE.sei,
    tokenStandard: 'Sei Chain',
    scan: 'https://www.seiscan.app/atlantic-2',
    rpcURL: 'https://rest.wallet.atlantic-2.sei.io',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'accounts',
    nameSuffix: 'Testnet',
    symbolSuffix: '',
  },
  seiMainnet: {
    prefix: 'sei',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,

    chainId: 'pacific-1',
    id: 'sei-network',
    name: 'Sei Mainnet',
    icon: 'app_sei',
    symbol: 'SEI',
    logo: COIN_IMAGE.SEI,
    chain: CHAIN_TYPE.seiMainnet,
    tokenStandard: 'Sei Chain',
    scan: 'https://www.seiscan.app/pacific-1',
    rpcURL: 'https://rpc.wallet.pacific-1.sei.io',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'accounts',
  },
  seiEvm: {
    id: 'sei',
    numChainId: 713715,
    prefix: 'sei',
    chainId: '0xae3f3',
    // isToken: true,
    environment: 'devnet',
    isWeb3: true,
    isFee: true,
    // isSupportedNFT: true,
    standard: 'SRC20',
    nftStandard: 'SRC721',
    name: 'Sei EVM Devnet',
    shortName: 'Sei EVM',
    icon: 'app_sei',
    logo: COIN_IMAGE.SHARDEM,
    symbol: 'SEI',
    chain: CHAIN_TYPE.seiEvm,
    scan: 'https://seitrace.com',
    // gasLimit: 35000000,
    replacementSymbol: 'EVM',

    tokenStandard: 'SRC20 SRC721',
    rpcURL: 'https://evm-rpc.arctic-1.seinetwork.io',
  },
  archway: {
    environment: 'devnet',
    prefix: 'archway',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,
    chainId: 'constantine-3',
    id: 'constantine-3',
    name: 'Archway Testnet',
    icon: 'app_archway',
    symbol: 'CONST',
    logo: COIN_IMAGE.CONST,
    chain: CHAIN_TYPE.archway,
    tokenStandard: 'Constantine Testnet',
    scan: 'https://testnet.mintscan.io/archway-testnet',
    rpcURL: 'https://rpc.constantine.archway.tech/',
    scanTxPrefix: 'txs',
    scanAddressPrefix: 'account',
  },
  // triomphe: {
  //   environment: 'mainnet',
  //   prefix: 'archway',
  //   path: 118,

  //   order: 3,
  //   isCosmos: true,
  //   isFactory: true,
  //   isMemo: true,
  //   isToken: false,
  //   chainId: 'archway-1',
  //   id: 'archway-1',
  //   name: 'Archway',
  //   icon: 'app_archway',
  //   symbol: 'CONST',
  //   logo: COIN_IMAGE.CONST,
  //   chain: CHAIN_TYPE.triomphe,
  //   tokenStandard: 'Constantine Mainnet',
  //   scan: 'https://mintscan.io/archway',
  //   rpcURL: 'https://rpc.mainnet.archway.io',
  //   scanTxPrefix: 'transactions',
  //   scanAddressPrefix: 'account'
  // },
  archwayMainnet: {
    environment: 'mainnet',
    prefix: 'archway',
    path: 118,

    order: 3,
    isCosmos: true,
    isFactory: true,
    isMemo: true,
    isToken: false,
    chainId: 'archway-1',
    id: 'archway-1',
    name: 'Archway',
    icon: 'app_archway',
    symbol: 'ARCH',
    logo: COIN_IMAGE.CONST,
    chain: CHAIN_TYPE.archwayMainnet,
    tokenStandard: 'Triomphe',
    scan: 'https://mintscan.io/archway',
    rpcURL: 'https://rpc.mainnet.archway.io',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'account',
  },

  chiliz: {
    id: 'chiliz',
    numChainId: 88888,
    chainId: '0x15B38',
    isToken: true,
    isWeb3: true,
    isFee: true,
    isDataField: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    standard: 'CAP20',
    isSupportedEIP1559: false,
    nftStandard: 'CAP721',
    name: 'Chiliz',
    shortName: 'CHZ',
    icon: 'app_chiliz',
    logo: COIN_IMAGE.CHZ,
    symbol: 'CHZ',
    chain: CHAIN_TYPE.chiliz,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',

    tokenStandard: 'CAP20 CAP721',
    rpcURL: 'https://rpc.chiliz.com/',
    scan: 'https://scan.chiliz.com/',
  },
  manta: {
    id: 'ethereum',
    replacementSymbol: 'MANTA', // replacementSymbol
    numChainId: 169,
    chainId: '0xa9',
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isL2: true,
    // isSupportedNFT: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'Manta Pacific',
    icon: 'app_manta',
    shortName: 'ETH',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.manta,
    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://pacific-rpc.manta.network/http',
    scan: 'https://pacific-explorer.manta.network',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  mantle: {
    id: 'mantle',
    numChainId: 5000,
    chainId: '0x1388',
    // isL2: true,
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'Mantle',
    shortName: 'Mantle',
    icon: 'app_mantle',
    logo: COIN_IMAGE.MNT,
    symbol: 'MNT',
    chain: CHAIN_TYPE.mantle,

    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',

    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://rpc.mantle.xyz:443',
    scan: 'https://explorer.mantle.xyz/',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  scroll: {
    id: 'ethereum',
    numChainId: 534352,
    chainId: '0x82750',
    isL2: true,
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'Scroll',
    shortName: 'Scroll',
    icon: 'app_scroll',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.scroll,
    replacementSymbol: 'SCROLL',

    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://rpc.scroll.io/',
    scan: 'https://scrollscan.com/',
    gasOracleAddress: '0x5300000000000000000000000000000000000002'
  },
  // scrollTestnet: {
  //   id: 'ethereum',
  //   numChainId: 534353,
  //   chainId: '0x82751',
  //   isToken: true,
  //   isWeb3: true,
  //   isFee: true,
  //   isSupportedNFT: true,
  //   standard: 'SRC20',
  //   nftStandard: 'SRC721',
  //   environment: 'testnet',
  //   name: 'Scroll Alpha Testnet',
  //   shortName: 'Scroll',
  //   icon: 'app_scroll',
  //   logo: COIN_IMAGE.ETH,
  //   symbol: 'ETH',
  //   replacementSymbol: 'SCROLL',
  //   // replacementSymbol: 'SCROLL',
  //   chain: CHAIN_TYPE.scrollTestnet,
  //   rapidNetwork: true,

  //   tokenStandard: 'SRC20 SRC721',
  //   rpcURL: 'https://scroll-testnet.blockpi.network/v1/rpc/public',
  //   scan: 'https://blockscout.scroll.io/',
  //   gasOracleAddress: '0x5300000000000000000000000000000000000002'
  // },
  nautilus: {
    id: 'zebec-protocol',
    numChainId: 22222,
    chainId: '0x56ce',
    isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'NRC20',
    nftStandard: 'NRC721',
    name: 'Nautilus',
    shortName: 'ZBC',
    icon: 'app_nautilus',
    logo: COIN_IMAGE.ZBC,
    symbol: 'ZBC',
    chain: CHAIN_TYPE.nautilus,
    tokenStandard: 'NRC20 NRC721',
    rpcURL: 'https://api.nautilus.nautchain.xyz',
    scan: 'https://nautscan.com/',
  },
  doge: {
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    isFee: true,
    isMnemonicOnly: true,
    icon: 'app_doge',
    id: 'dogecoin',
    name: 'Dogecoin',
    shortName: 'Dogecoin',
    logo: COIN_IMAGE.DOGE,
    symbol: 'DOGE',
    chain: CHAIN_TYPE.doge,
    tokenStandard: 'DOGE',
    scan: 'https://dogechain.info',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  bitkub: {
    id: 'bitkub-coin',
    numChainId: 96,
    chainId: '0x60',
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'KAP20',
    nftStandard: 'KAP721',
    name: 'Bitkub Chain',
    shortName: 'Bitkub',
    icon: 'app_bitkub',
    logo: COIN_IMAGE.BITKUB,
    symbol: 'KUB',
    chain: CHAIN_TYPE.bitkub,

    tokenStandard: 'KAP20 KAP721',
    rpcURL: 'https://rpc.bitkubchain.io/',
    scan: 'https://www.bkcscan.com/',
    balanceContract: '0x9aE5c1cf82aF51CBB83D9A7B1C52aF4B48E0Bb5E',
    multiTransferContract: '0xaEC945e04baF28b135Fa7c640f624f8D90F1C3a6',
  },
  zetaMainnet: {
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    id: 'zetachain',
    numChainId: 7000,
    chainId: '0x1b58',
    isToken: true,
    isWeb3: true,
    isFee: true,
    // isSupportedNFT: true,
    standard: 'ZRC20',
    nftStandard: 'ZRC721',
    name: 'ZetaChain',
    shortName: 'zeta',
    icon: 'app_zeta',
    logo: COIN_IMAGE.ZETA,
    symbol: 'ZETA',
    chain: CHAIN_TYPE.zetaMainnet,
    tokenStandard: 'ZRC20 ZRC721',
    rpcURL: 'https://zetachain-evm.blockpi.network/v1/rpc/public',
    scan: 'https://zetachain.blockscout.com',
  },
  zeta: {
    id: 'zetachain',
    numChainId: 7001,
    chainId: '0x1b59',
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'ZetaChain Testnet',
    shortName: 'zeta',
    icon: 'app_zeta',
    logo: COIN_IMAGE.ZETA,
    symbol: 'AZETA',
    chain: CHAIN_TYPE.zeta,
    environment: 'testnet',

    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://zetachain-testnet.public.blastapi.io',
    scan: 'https://athens.explorer.zetachain.com',
    scanTxPrefix: 'evm/tx',
  },
  humanode: {
    id: 'humanode',
    numChainId: 5234,
    chainId: '0x1472',
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'Humanode',
    shortName: 'Humanode',
    icon: 'app_humanode',
    logo: COIN_IMAGE.HUMANODE,
    symbol: 'eHMND',
    chain: CHAIN_TYPE.humanode,

    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://explorer-rpc-http.mainnet.stages.humanode.io',
    scan: 'https://humanode.subscan.io',
  },
  opBNB: {
    id: 'binancecoin',
    numChainId: 204,
    chainId: '0xcc',
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'opBNB',
    shortName: 'opBNB',
    icon: 'app_binance',
    logo: COIN_IMAGE.BNB,
    symbol: 'BNB',
    chain: CHAIN_TYPE.opBNB,
    // multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    // balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://opbnb-mainnet-rpc.bnbchain.org/',
    replacementSymbol: 'opBNB',
    scan: 'https://opbnbscan.com',
  },
  shardeum: {
    id: 'shardeum',
    numChainId: 8081,
    chainId: '0x1f91',
    // isToken: true,
    isWeb3: true,
    isFee: true,
    isSupportedNFT: true,
    standard: 'MRC20',
    nftStandard: 'MRC721',
    name: 'Shardeum Testnet',
    shortName: 'Shardeum',
    icon: 'app_shardeum',
    logo: COIN_IMAGE.SHARDEM,
    symbol: 'SHM',
    chain: CHAIN_TYPE.shardeum,
    environment: 'testnet',

    tokenStandard: 'MRC20 MRC721',
    rpcURL: 'https://dapps.shardeum.org/',
    scan: 'https://explorer-dapps.shardeum.org/',
  },
  xrp: {
    isFee: true,
    isMemo: true,
    isMnemonicOnly: true,
    icon: 'app_xrp',
    id: 'ripple',
    name: 'XRP Ledger',
    shortName: 'ripple',
    logo: COIN_IMAGE.XRP,
    symbol: 'XRP',
    chain: CHAIN_TYPE.xrp,
    tokenStandard: 'XRP',
    scan: 'https://xrpscan.com',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'account',
    isSupportedNFT: false,
    isCrawlNFTServices: true,
  },
  xion: {
    prefix: 'xion',
    path: 118,
    // isToken: true,
    // standard: 'CW20',
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'xion',
    chainId: 'xion-testnet-1',

    name: 'Xion Testnet',
    environment: 'testnet',
    icon: 'app_xion',
    symbol: 'XION',
    logo: COIN_IMAGE.XION,
    chain: CHAIN_TYPE.xion,
    tokenStandard: 'CW20',
    scan: 'https://explorer.burnt.com/xion-testnet-1',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'account',
    isSupportedNFT: false,
  },
  celestia: {
    prefix: 'celestia',
    path: 118,
    // isToken: true,
    // standard: 'CW20',
    isFactory: true,
    isCosmos: true,
    isMemo: true,

    id: 'celestia',
    chainId: 'celestia',
    name: 'Celestia',
    icon: 'app_celestia',
    symbol: 'TIA',
    logo: COIN_IMAGE.LUNA2,
    chain: CHAIN_TYPE.celestia,
    // tokenStandard: 'LUNA CW20',
    scan: 'https://www.mintscan.io/celestia',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'account',
    isSupportedNFT: false,
  },
  cardano: {
    isFee: true,
    isMnemonicOnly: true,
    icon: 'app_cardano',
    id: 'cardano',
    name: 'Cardano',
    shortName: 'cardano',
    logo: COIN_IMAGE.CARDANO,
    symbol: 'ADA',
    chain: CHAIN_TYPE.cardano,
    tokenStandard: 'ADA',
    scan: 'https://cardanoscan.io/',
    scanTxPrefix: 'transaction',
    scanAddressPrefix: 'address',
    isSupportedNFT: false,
  },
  starknet: {
    replacementSymbol: 'STARKNET',
    isFee: true,
    icon: 'app_starknet',
    id: 'starknet',
    name: 'Starknet',
    shortName: 'Starknet',
    logo: COIN_IMAGE.ETH,
    symbol: 'STRK',
    chain: CHAIN_TYPE.starknet,
    tokenStandard: 'ETH ERC20 ERC721',
    scan: 'https://starkscan.co',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'contract',
    isSupportedNFT: false,
    isL2: true,
  },
  zkFair: {
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    id: 'usd-coin',
    replacementSymbol: 'ZKFAIR',
    isToken: true,
    numChainId: 42766,
    chainId: '0xa70e',
    standard: 'ZRC20',
    nftStandard: 'ZRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_zkFair',
    name: 'ZKFair',
    shortName: 'USDC',
    symbol: 'USDC',
    chain: CHAIN_TYPE.zkFair,
    tokenStandard: 'ZRC20 ZRC721',
    rpcURL: 'https://rpc.zkfair.io',
    scan: 'https://scan.zkfair.io',
  },
  beam: {
    numChainId: 4337,
    chainId: '0x10f1',
    balanceContract: '0x6c041CD1e064a7845f7734BEf42456c7E6b6E617',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    standard: 'ERC20 ERC721',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isSupportedNFT: true,
    id: 'beam',
    icon: 'app_beam',
    name: 'Beam',
    shortName: 'Beam',
    symbol: 'BEAM',
    chain: CHAIN_TYPE.beam,
    tokenStandard: 'ERC20',
    rpcURL: 'https://build.onbeam.com/rpc',
    scan: 'https://subnets.avax.network/beam'
  },
  rootstock: {
    numChainId: 30,
    chainId: '0x1e',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    standard: 'ERC-20 ERC721',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isSupportedNFT: true,
    id: 'rootstock',
    icon: 'app_rootstock',
    name: 'Rootstock Mainnet',
    shortName: 'RabBitcoin',
    symbol: 'RBTC',
    chain: CHAIN_TYPE.rootstock,
    tokenStandard: 'ERC-20 ERC721',
    rpcURL: 'https://mycrypto.rsk.co',
    scan: 'https://explorer.rootstock.io'
  },
  morph: {
    numChainId: 2818,
    balanceContract: '0x4d461b38d1753386D4d6797F79441Ed0adC2f6F8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    chainId: '0xb02',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    id: 'ethereum',
    isL2: true,
    // id: 'ethereum',
    icon: 'app_morph',
    name: 'Morph',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.morph,
    replacementSymbol: 'MORPH',
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.morphl2.io',
    scan: 'https://explorer.morphl2.io',
  },
  plume: {
    numChainId: 98865,
    balanceContract: '0x4d461b38d1753386D4d6797F79441Ed0adC2f6F8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    chainId: '0x18231',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'ethereum',
    icon: 'app_plume',
    name: 'Plume Mainnet',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.plume,
    replacementSymbol: 'PLUME',
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.plumenetwork.xyz',
    scan: 'https://explorer.plumenetwork.xyz',
  },
  sonic: {
    numChainId: 146,
    balanceContract: '0x4d461b38d1753386D4d6797F79441Ed0adC2f6F8',
    multiTransferContract: '0x67807b9f5B9757C0c79347F0b3f360C15c5E6aFF',
    chainId: '0x92',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    id: 'sonic-3',
    icon: 'app_sonic',
    name: 'Sonic',
    shortName: 'S',
    symbol: 'S',
    chain: CHAIN_TYPE.sonic,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://sonic-rpc.publicnode.com',
    scan: 'https://sonicscan.org/'
  },

  // omni: {
  //   environment: 'testnet',
  //   balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
  //   multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  //   isToken: true,
  //   numChainId: 165,
  //   chainId: '0xa5',
  //   standard: 'ORC20',
  //   nftStandard: 'OC721',
  //   isWeb3: true,
  //   isFee: true,
  //   icon: 'app_omni',
  //   name: 'Omni Testnet',
  //   shortName: 'OMNI',
  //   symbol: 'OMNI',
  //   chain: CHAIN_TYPE.omni,
  //   tokenStandard: 'ORC20 ORC721',
  //   rpcURL: 'https://testnet.omni.network',
  //   scan: 'https://testnet.explorer.omni.network',
  // },
  // orderly: {
  //   balanceContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
  //   multiTransferContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  //   id: 'ethereum',
  //   replacementSymbol: 'ORDERLY',
  //   isToken: true,
  //   isL2: true,
  //   numChainId: 291,
  //   chainId: '0x123',
  //   standard: 'ORC20',
  //   nftStandard: 'ORC721',
  //   isWeb3: true,
  //   isFee: true,
  //   icon: 'app_orderly',
  //   name: 'Orderly Network',
  //   shortName: 'ETH',
  //   symbol: 'ETH',
  //   chain: CHAIN_TYPE.orderly,
  //   tokenStandard: 'ORC20 ORC721',
  //   rpcURL: 'https://rpc.orderly.network',
  //   scan: 'https://explorer.orderly.network:443'
  // },
  skate: {
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    replacementSymbol: 'SKATE',
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    environment: 'testnet',
    isL2: true,
    numChainId: 5051,
    chainId: '0x13bb',
    standard: 'SRC20',
    nftStandard: 'SRC721',
    isWeb3: true,
    isFee: true,
    icon: 'app_skate',
    name: 'Nollie Skatechain Testnet',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.skate,
    tokenStandard: 'SRC20 SRC721',
    rpcURL: 'https://nollie-rpc.skatechain.org',
    scan: 'https://nolliescan.skatechain.org',
  },
  wanchain: {
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    id: 'wanchain',
    isToken: true,
    numChainId: 888,
    chainId: '0x378',
    standard: 'WRC20',
    nftStandard: 'WRC721',
    isWeb3: true,
    isSupportedEIP1559: false,
    isFee: true,
    icon: 'app_wanchain',
    name: 'Wanchain',
    shortName: 'WAN',
    symbol: 'WAN',
    chain: CHAIN_TYPE.wanchain,
    tokenStandard: 'WRC20 WRC721',
    rpcURL: 'https://gwan-ssl.wandevs.org:56891',
    scan: 'https://www.wanscan.org',
  },
  mint: {
    replacementSymbol: 'MINT',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    isCrawlServices: true,
    numChainId: 185,
    chainId: '0xb9',
    standard: 'ERC20 MINT',
    nftStandard: 'ERC721 MINT',
    isWeb3: true,
    isToken: true,
    isFee: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    icon: 'app_mintchain',
    name: 'Mint',
    shortName: 'ETH',
    id: 'ethereum',
    isL2: true,
    symbol: 'ETH',
    chain: CHAIN_TYPE.mint,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.mintchain.io',
    scan: 'https://explorer.mintchain.io:443',
    gasOracleAddress: '0x420000000000000000000000000000000000000F'
  },
  iotex: {
    prefix: 'io',
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    isCrawlServices: true,
    numChainId: 4689,
    chainId: '0x1251',
    standard: 'XRC20',
    nftStandard: 'XRC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    icon: 'app_iotex',
    id: 'iotex',
    name: 'IoTeX Network',
    shortName: 'IOTX',
    symbol: 'IOTX',
    chain: CHAIN_TYPE.iotex,
    tokenStandard: 'XRC20 XRC721',
    gasUnit: 'Qev',
    gasDecimal: 12,
    rpcURL: 'https://rpc.ankr.com/iotex',
    scan: 'https://iotexscan.io/',
  },
  zkLink: {
    replacementSymbol: 'ZKLINK',
    // balanceContract: '0x9F48912d11C10eE8b1eCc38594972477bB53F1a6',
    // multiTransferContract: '0x101a473722ee9B1D861C58aE0e2F25434870A74d',
    isCrawlServices: true,
    numChainId: 810180,
    chainId: '0xc5cc4',
    standard: 'ERC20 ZKLINK',
    nftStandard: 'ERC721 ZKLINK',
    isToken: true,
    isWeb3: true,
    isFee: true,
    icon: 'app_zkLink',
    name: 'zkLink Nova',
    shortName: 'ETH',
    isL2: true,
    id: 'ethereum',
    logo: COIN_IMAGE.ETH,
    symbol: 'ETH',
    chain: CHAIN_TYPE.zkLink,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.zklink.io',
    scan: 'https://explorer.zklink.io',
  },
  neon: {
    numChainId: 245022934,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    isCrawlServices: true,
    chainId: '0xe9ac0d6',
    id: 'neon',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isToken: true,
    isDataField: true,
    isFee: true,
    icon: 'app_neon',
    name: 'Neon EVM',
    shortName: 'NEON',
    symbol: 'NEON',
    chain: CHAIN_TYPE.neon,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://neon-proxy-mainnet.solana.p2p.org',
    scan: 'https://neonscan.org',
    gasUnit: 'Galan'
  },
  auraEvm: {
    replacementSymbol: 'EVM',
    numChainId: 6322,
    chainId: '0x18b2',
    standard: 'EVM ERC20',
    prefix: 'aura',
    balanceContract: '0x6509A9977569413CE8baCa7C50BeA0F2F983E53B',
    multiTransferContract: '0x963e1BcD1f82724bD8Fa16a3B6962D100fB287FC',
    nftStandard: 'EVM ERC721',
    id: 'aura-network',
    isWeb3: true,
    isFee: true,
    isCrawlNFTServices: true,
    isSupportedNFT: true,
    isToken: true,
    icon: 'app_aura_network',
    logo: COIN_IMAGE.AURA,
    name: 'Aura EVM',
    shortName: 'AURA',
    symbol: 'AURA',
    chain: CHAIN_TYPE.auraEvm,
    tokenStandard: 'ERC20 ERC721 AURA',
    rpcURL: 'https://jsonrpc.aura.network',
    scan: 'https://aurascan.io',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'address',
  },
  xLayer: {
    numChainId: 196,
    balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
    multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
    chainId: '0xc4',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    id: 'okb',
    icon: 'app_xLayer',
    name: 'X Layer',
    shortName: 'X Layer',
    symbol: 'OKB',
    chain: CHAIN_TYPE.xLayer,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.xlayer.tech',
    scan: 'https://www.oklink.com/xlayer',
  },
  cyber: {
    numChainId: 7560,
    balanceContract: '0x7ff3be07ffa286b2806ac458ce9982a73611537e',
    multiTransferContract: '0x6c041cd1e064a7845f7734bef42456c7e6b6e617',
    chainId: '0x1d88',
    standard: 'ERC20 CYBER',
    nftStandard: 'ERC721 CYBER',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'ethereum',
    icon: 'app_cyber',
    name: 'Cyber',
    shortName: 'ETH',
    symbol: 'ETH',
    replacementSymbol: 'CYBER',
    chain: CHAIN_TYPE.cyber,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://cyber-mainnet-archive.alt.technology',
    scan: 'https://cyberscan.co',
  },
  xterio: {
    numChainId: 2702128,
    balanceContract: '0x40A2b4d38a55afc5a6731c69b616326177D294Ce',
    multiTransferContract: '0x6c041CD1e064a7845f7734BEf42456c7E6b6E617',
    chainId: '0x293b30',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'ethereum',
    icon: 'app_xterio',
    name: 'Xterio',
    shortName: 'ETH',
    symbol: 'ETH',
    replacementSymbol: 'XTERIO',
    chain: CHAIN_TYPE.xterio,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://xterio-eth.alt.technology',
    scan: 'https://eth.xterscan.io'
  },
  astar: {
    numChainId: 3776,
    balanceContract: '0xD4825105467044301bc6B89EcEA42Bde24F152FD',
    multiTransferContract: '0x40A2b4d38a55afc5a6731c69b616326177D294Ce',
    chainId: '0xec0',
    standard: 'ERC20 ASTAR',
    nftStandard: 'ERC721 ASTAR',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'ethereum',
    icon: 'app_astar',
    name: 'Astar zkEVM',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.astar,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.startale.com/astar-zkevm',
    scan: 'https://astar-zkevm.explorer.startale.com',
    replacementSymbol: 'ASTAR'
  },
  fraxtal: {
    numChainId: 252,
    balanceContract: '0x40A2b4d38a55afc5a6731c69b616326177D294Ce',
    multiTransferContract: '0x6c041CD1e064a7845f7734BEf42456c7E6b6E617',
    chainId: '0xfc',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'frax-ether',
    icon: 'app_fraxtal',
    name: 'Fraxtal',
    shortName: 'Frax Ether',
    symbol: 'FRXETH',
    chain: CHAIN_TYPE.fraxtal,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.mainnet.frax.com/',
    scan: 'https://fraxscan.com'
  },
  lightLink: {
    numChainId: 1890,
    balanceContract: '0x40A2b4d38a55afc5a6731c69b616326177D294Ce',
    multiTransferContract: '0x6c041CD1e064a7845f7734BEf42456c7E6b6E617',
    chainId: '0x762',
    standard: 'ERC20 LIGHTLINK',
    nftStandard: 'ERC721 LIGHTLINK',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'ethereum',
    icon: 'app_lightLink',
    name: 'Lightlink Phoenix',
    shortName: 'ETH',
    symbol: 'ETH',
    replacementSymbol: 'LIGHTLINK',
    chain: CHAIN_TYPE.lightLink,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://replicator-01.phoenix.lightlink.io/rpc/v1',
    scan: 'https://phoenix.lightlink.io'
  },
  zircuit: {
    numChainId: 48900,
    balanceContract: '0x40A2b4d38a55afc5a6731c69b616326177D294Ce',
    multiTransferContract: '0x6c041CD1e064a7845f7734BEf42456c7E6b6E617',
    chainId: '0xbf04',
    standard: 'ERC20 ZIRCUIT',
    nftStandard: 'ERC721 ZIRCUIT',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'ethereum',
    icon: 'app_zircuit',
    name: 'Zircuit',
    shortName: 'ETH',
    symbol: 'ETH',
    replacementSymbol: 'ZIRCUIT',
    chain: CHAIN_TYPE.zircuit,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://zircuit1-mainnet.p2pify.com/',
    scan: 'https://explorer.zircuit.com'
  },
  orange: {
    balanceContract: '0x7FF3BE07Ffa286B2806ac458cE9982A73611537E',
    multiTransferContract: '0xD4825105467044301bc6B89EcEA42Bde24F152FD',
    numChainId: 61022,
    chainId: '0xee5e',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    id: 'bitcoin',
    icon: 'app_orange',
    name: 'Orange',
    shortName: 'BTC',
    symbol: 'BTC',
    replacementSymbol: 'ORANGE',
    chain: CHAIN_TYPE.orange,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://hk-rpc.orangechain.xyz',
    scan: 'https://scan.orangechain.xyz'
  },
  abstract: {
    environment: 'testnet',
    numChainId: 11124,
    // balanceContract: '',
    // multiTransferContract: '',
    chainId: '0x2b74',
    standard: 'ERC20',
    nftStandard: 'ERC721',
    isWeb3: true,
    isFee: true,
    isToken: true,
    isL2: true,
    // id: 'ethereum',
    icon: 'app_abstract',
    name: 'Abstract Testnet',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.abstract,
    replacementSymbol: 'ABSTRACT',
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://api.testnet.abs.xyz',
    scan: 'https://explorer.testnet.abs.xyz',
  },
  stellar: {
    chainId: 'stellar',
    tokenStandard: 'SEP-41',
    id: 'stellar',
    name: 'Stellar',
    shortName: 'Stellar',
    icon: 'app_stellar',
    symbol: 'XLM',
    chain: CHAIN_TYPE.stellar,
    standard: 'SEP-41',
    rpcURL: 'https://svc.blockdaemon.com/stellar/mainnet/native/soroban-rpc?apiKey=zpka_a5d1f92a23ba40999d916e148b93e348_029ad9e2',
    scan: 'https://stellar.expert/explorer/public',
    scanTxPrefix: 'tx',
    scanAddressPrefix: 'account',
  },
  pi: {
    chainId: 'pi-network',
    tokenStandard: 'SEP-41',
    id: 'pi-network',
    name: 'Pi Network',
    shortName: 'Pi',
    icon: 'app_pi',
    symbol: 'PI',
    chain: CHAIN_TYPE.pi,
    standard: 'SEP-41',
    rpcURL: 'https://api.mainnet.minepi.com',
    scan: 'https://blockexplorer.minepi.com/mainnet',
    scanTxPrefix: 'transactions',
    scanAddressPrefix: 'accounts',
  },
  polygonTestnet: {
    environment: 'testnet',
    numChainId: 80002,
    chainId: '0x13882',
    // replacementSymbol: 'POL',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_polygon',
    balanceContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    multiTransferContract: '0xde7d7F5625417387b64817A22C7E1B7DC18dA0c6',
    name: 'Amoy',
    shortName: 'POL',
    symbol: 'POL',
    chain: CHAIN_TYPE.polygonTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://polygon-amoy.drpc.org',
    scan: 'https://amoy.polygonscan.com'
  },
  optimismSepoTestnet: {
    environment: 'testnet',
    numChainId: 11155420,
    chainId: '0xaa37dc',
    replacementSymbol: 'OP',
    isL2: true,
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_optimism',
    balanceContract: '0x3a0F399b45161D2F6D9E93419c56E6DA8e49392c',
    multiTransferContract: '0xC8C2CB5718BEd89F3c49C4cbc22F4A42f491865D',
    name: 'OP Sepolia Testnet',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.optimismSepoTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://optimism-sepolia.blockscout.com/api/eth-rpc',
    scan: 'https://sepolia-optimism.etherscan.io'
  },
  // okexTestnet: {
  //   environment: 'testnet',
  //   numChainId: 65,
  //   chainId: '0x41',
  //   replacementSymbol: 'OKX',
  //   // numLoad: 2,
  //   isToken: true,
  //   isSupportedNFT: true,
  //   isCrawlNFTServices: true,
  //   isDataField: true,
  //   standard: 'KIP10 Testnet',
  //   nftStandard: 'KIP20 Testnet',
  //   isWeb3: true,
  //   isFee: true,
  //   icon: 'app_okex',
  //   balanceContract: '0xf7eEe3A8363731C611A24CdDfCBcaDE9C153Cfe8',
  //   multiTransferContract: '0x5C93F4B35d3dD97Ef481881aA33d00F76806FdAD',
  //   name: 'OKExChain Testnet',
  //   shortName: 'OKT',
  //   symbol: 'OKT',
  //   chain: CHAIN_TYPE.okexTestnet,
  //   tokenStandard: 'KIP10 KIP20',
  //   rpcURL: 'https://exchaintestrpc.okex.org',
  //   scan: 'https://www.oklink.com/oktc'
  // },
  moonbeamTestnet: {
    environment: 'testnet',
    numChainId: 1287,
    chainId: '0x507',
    // numLoad: 2,
    replacementSymbol: 'MOONBASE',

    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'MERC20 TESTNET',
    nftStandard: 'MERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_moonbeam',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    name: 'Moonbase Alpha',
    shortName: 'DEV',
    symbol: 'DEV',
    chain: CHAIN_TYPE.moonbeamTestnet,
    tokenStandard: 'MERC20 MERC721',
    rpcURL: 'https://moonbase-alpha.drpc.org',
    scan: 'https://moonbase.moonscan.io/'
  },
  metisSepoTestnet: {
    environment: 'testnet',
    numChainId: 59902,
    chainId: '0xe9fe',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_metis',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    name: 'Metis Sepolia Testnet',
    shortName: 'tMETIS',
    symbol: 'tMETIS',
    chain: CHAIN_TYPE.metisSepoTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://sepolia.metisdevops.link',
    scan: 'https://sepolia-explorer.metisdevops.link'
  },
  fantomTestnet: {
    environment: 'testnet',
    numChainId: 4002,
    chainId: '0xfa2',
    // replacementSymbol: 'FMT',

    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_fantom',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    name: 'Fantom Testnet',
    shortName: 'FTM',
    symbol: 'FTM',
    chain: CHAIN_TYPE.fantomTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://fantomnet.public.blastapi.io',
    scan: 'https://testnet.ftmscan.com/'
  },
  etherSepoTestnet: {
    environment: 'testnet',
    numChainId: 11155111,
    chainId: '0xaa36a7',
    replacementSymbol: 'SEPOLIA',

    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_ethereum',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    name: 'Sepolia',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.etherSepoTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://eth-sepolia.blockscout.com/api/eth-rpc',
    scan: 'https://sepolia.etherscan.io'
  },
  bobaSepoTestnet: {
    isL2: true,
    environment: 'testnet',
    numChainId: 28882,
    chainId: '0x70d2',
    replacementSymbol: 'BOBA',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_boba',
    balanceContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    multiTransferContract: '0xde7d7F5625417387b64817A22C7E1B7DC18dA0c6',
    name: 'Boba Sepolia',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.bobaSepoTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://sepolia.boba.network',
    scan: 'https://sepolia.testnet.bobascan.com'
  },
  binanceSmartTestnet: {
    environment: 'testnet',
    numChainId: 97,
    chainId: '0x61',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'BRC20 TESTNET',
    nftStandard: 'BRC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_binance',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    name: 'BNB Smart Chain Testnet',
    shortName: 'tBNB',
    symbol: 'tBNB',
    chain: CHAIN_TYPE.binanceSmartTestnet,
    tokenStandard: 'BRC20 BRC721',
    rpcURL: 'https://go.getblock.io/24e1bff26d884cf38ff5f18793837b7e',
    scan: 'https://testnet.bscscan.com'
  },
  avaxFujiTestnet: {
    environment: 'testnet',
    numChainId: 43113,
    chainId: '0xa869',
    // replacementSymbol: 'AVAX',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_avalancher',
    balanceContract: '0x77037B39E5b7222F354E97B5920E1b7459808D12',
    multiTransferContract: '0x915eaA3193362f9219D607Af0451be7275a18DB7',
    name: 'Avalanche Fuji Testnet',
    shortName: 'AVAX',
    symbol: 'AVAX',
    chain: CHAIN_TYPE.avaxFujiTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://avalanche-fuji-c-chain-rpc.publicnode.com',
    scan: 'https://subnets.avax.network/c-chain'
  },
  auroraTestnet: {
    isL2: true,
    environment: 'testnet',
    numChainId: 1313161555,
    chainId: '0x4e454153',
    replacementSymbol: 'AURORA',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_aurora',
    balanceContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    multiTransferContract: '0xde7d7F5625417387b64817A22C7E1B7DC18dA0c6',
    name: 'Aurora Testnet',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.auroraTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://testnet.aurora.dev',
    scan: 'https://explorer.testnet.aurora.dev'
  },
  arbitrumSepoTestnet: {
    isL2: true,
    environment: 'testnet',
    numChainId: 421614,
    chainId: '0x66eee',
    replacementSymbol: 'ARB',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_arbitrum',
    balanceContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    multiTransferContract: '0xde7d7F5625417387b64817A22C7E1B7DC18dA0c6',
    name: 'Arbitrum Sepolia',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.arbitrumSepoTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://sepolia-rollup.arbitrum.io/rpc',
    scan: 'https://sepolia.arbiscan.io/'
  },
  minatoTestnet: {
    isL2: true,
    environment: 'testnet',
    numChainId: 1946,
    chainId: '0x79a',
    replacementSymbol: 'MINATO',
    // numLoad: 2,
    isToken: true,
    isSupportedNFT: true,
    isCrawlNFTServices: true,
    isDataField: true,
    standard: 'ERC20 TESTNET',
    nftStandard: 'ERC721 TESTNET',
    isWeb3: true,
    isFee: true,
    icon: 'app_minato',
    balanceContract: '0x1357Fd6B499d390c514f7CeD9107979003A5da74',
    multiTransferContract: '0xe4b61007447F62d4be98e42843ef804ad0Ae3aDc',
    name: 'Soneium Minato Testnet',
    shortName: 'ETH',
    symbol: 'ETH',
    chain: CHAIN_TYPE.minatoTestnet,
    tokenStandard: 'ERC20 ERC721',
    rpcURL: 'https://rpc.minato.soneium.org',
    scan: 'https://explorer-testnet.soneium.org'
  },
   story: {
      id: 'story-2',
      isToken: true,
      balanceContract: '0x6c041CD1e064a7845f7734BEf42456c7E6b6E617',
      multiTransferContract: '0x40A2b4d38a55afc5a6731c69b616326177D294Ce',
      numChainId: 1514,
      chainId: '0x5ea',
      logo: COIN_IMAGE.STORY,
      isWeb3: true,
      icon: 'app_story',
      name: 'Story Mainnet',
      shortName: 'IP',
      symbol: 'IP',
      chain: CHAIN_TYPE.story,
      tokenStandard: 'ERC20 ERC721',
      rpcURL: 'https://evm-rpc.story.mainnet.dteam.tech',
      scan: 'https://storyscan.xyz'
    },
    monadTestnet: {
      environment: 'testnet',
      numChainId: 10143,
      chainId: '0x279f',
      // numLoad: 2,
      isToken: true,
      isSupportedNFT: true,
      isDataField: true,
      standard: 'ERC20 TESTNET',
      nftStandard: 'ERC721 TESTNET',
      isWeb3: true,
      isFee: true,
      icon: 'app_monad',
      balanceContract: '',
      multiTransferContract: '',
      name: 'Monad Testnet',
      shortName: 'MON',
      symbol: 'MON',
      chain: CHAIN_TYPE.monadTestnet,
      tokenStandard: 'ERC20 ERC721',
      rpcURL: 'https://testnet-rpc.monad.xyz',
      scan: 'https://monad-testnet.socialscan.io'
    },
    somnia: {
      environment: 'testnet',
      numChainId: 50312,
      chainId: '0xc488',
      // numLoad: 2,
      isToken: true,
      isSupportedNFT: true,
      isDataField: true,
      standard: 'ERC20 TESTNET',
      nftStandard: 'ERC721 TESTNET',
      isWeb3: true,
      isFee: true,
      icon: 'app_somnia',
      balanceContract: '0x4d461b38d1753386D4d6797F79441Ed0adC2f6F8',
      multiTransferContract: '0xD4825105467044301bc6B89EcEA42Bde24F152FD',
      name: 'Somnia Testnet',
      shortName: 'STT',
      symbol: 'STT',
      chain: CHAIN_TYPE.somnia,
      tokenStandard: 'ERC20 ERC721',
      rpcURL: 'https://rpc.ankr.com/somnia_testnet/6e3fd81558cf77b928b06b38e9409b4677b637118114e83364486294d5ff4811',
      scan: 'https://shannon-explorer.somnia.network'
    },
} as const;

export const ChainData = Object.keys(CHAIN_DATA)
  .filter((k) => !CHAIN_DATA[k].isExcluded)
  .map((k) => CHAIN_DATA[k])

export const SORTED_CHAIN_LIST = ChainData.map((c) => c.chain)